config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => { :sign_in => "users/sign_in", :sign_out => "users/sign_out" }
  root to: "bills#index"
  resources :bills
  resources :categories
  resources :companies
  resources :models
  resources :imported_items
  resources :stocks, only: :index
  get "set_items", to: 'companies#set_items'
  get "set_price", to: 'companies#set_price'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :item
  validates_presence_of :name, :father_name, :address, :price, :mobile_no

end

app/models/imported_item.rb
class ImportedItem < ApplicationRecord
  belongs_to :item
  validates_presence_of :imported_date, :quantity, :price_per_unit
  before_create do
    self.total_price = self.quantity * self.price_per_unit
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :sub_items, class_name: "Item", foreign_key: "parrent_id"
  belongs_to :parrent, class_name: "Item", optional: true
  has_many :imported_items
  has_many :bills
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = Bill.all
  end

  def new
    @categories = Item.where(item_type: 'category')
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)

    if @bill.save
      redirect_to bills_path
    else
      @categories = Item.where(item_type: 'category')
      render :new
    end
  end

  private

    def bill_params
      params.require(:bill).permit(:name, :father_name, :address, :mobile_no, :price, :item_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Item.where(item_type: 'category')
  end

  def new
    @category = Item.new
  end

  def create
    @category = Item.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.permit(:name, :item_type)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Item.where(item_type: 'company')
  end

  def new
    @categories = Item.where(item_type: 'category')
    redirect_to root_path, alert: 'Please create Category first.' if @categories.blank?
    @company = Item.new
  end

  def create
    @company = Item.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      @categories = Item.where(item_type: 'category')
      render :new
    end
  end

  def set_items
    item = Item.find(params[:id])
    @items = item.sub_items
  end

  def set_price
    model = Item.find(params[:id])
    @price = model.imported_items.last.price_per_unit
    profit = model.imported_items.last.profit
    @price += (@price * profit )/100
  end

  private

  def company_params
    params.permit(:name, :item_type, :parrent_id)
  end
end

app/controllers/imported_items_controller.rb
class ImportedItemsController < ApplicationController
  def index
    @imported_items = ImportedItem.all
  end

  def new
    @categories = Item.where(item_type: 'category')
    @imported_item = ImportedItem.new
  end

  def create
    @imported_item = ImportedItem.new(imported_item_params)
    if @imported_item.save
      redirect_to imported_items_path
    else
      @categories = Item.where(item_type: 'category')
      render :new
    end
  end

  private

  def imported_item_params
    params.require(:imported_item).permit(:imported_date, :quantity, :price_per_unit, :item_id, :profit)
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def index
    @models = Item.where(item_type: 'model')
  end

  def new
    @categories = Item.where(item_type: 'category')
    @model = Item.new
  end

  def create
    @model = Item.new(model_params)
    if @model.save
      redirect_to models_path
    else
      @categories = Item.where(item_type: 'category')
      render :new
    end
  end

  private

  def model_params
    params.permit(:name, :item_type, :parrent_id)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = ImportedItem.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/stocks_helper.rb
# frozen_string_literal: true

module StocksHelper
  def sort_stocks(stocks)
    temp = []
    stocks.each do |stock|
      if temp.map { |a| a.key?(stock.item.name) }.include?(true)
        temp.each do |tem|
          if tem.key?(stock.item.name)
            tem[stock.item.name]['stocks'] << stock
            tem[stock.item.name]['quantity'] << stock.quantity
          end
        end
      else
        temp << { stock.item.name => { 'stocks' => [stock], 'quantity' => [stock.quantity] } }
        update_quantity_from_bill(stock, temp)
      end
    end
    add_quantity(temp)
  end

  def add_quantity(array, stocks = [])
    array.each do |item|
      item.each do |_key, value|
        value['stocks'].first.quantity = value['quantity'].sum
        stocks << value['stocks'].first
      end
    end
    stocks
  end

  def update_quantity_from_bill(stock, temp)
    stock.item.bills.each do |bill|
      temp.last[stock.item.name]['quantity'].prepend(temp.last[stock.item.name]['quantity'].first - 1)
      temp.last[stock.item.name]['quantity'].pop
    end
  end
end

app/views/bills/index.html.erb
<h2>Bills</h2>
<%= link_to 'Create Bill', new_bill_path, class: "text-primary" %>

<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Name </th>
        <th> Father Name </th>
        <th> Address </th>
        <th> Date </th>
        <th> Mobile No. </th>
        <th> Catagory </th>
        <th> Company </th>
        <th> Model </th>
        <th> Price </th>
      </tr>
    </thead>
    <tbody>
      <% prices = [] %>
      <% @bills.each do |bill| %>
        <% prices << bill.price %>
        <tr>
          <th><%= sr %></th>
          <td><%= bill.name %></td>
          <td><%= bill.father_name %></td>
          <td><%= bill.address %></td>
          <td><%= bill.created_at.strftime("%d/%m/%y") %></td>
          <td><%= bill.mobile_no %></td>
          <td><%= bill.item.parrent.parrent.name %></td>
          <td><%= bill.item.parrent.name %></td>
          <td><%= bill.item.name %></td>
          <td><%= bill.price %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
      <tr bgcolor="yellow">
        <th colspan="9">Total Price</th>
        <th><%= prices.sum %></th>
      </tr>
    </tbody>
  </table>
</ul>

app/views/bills/new.html.erb
<h2>Create Bill</h2><hr>
<%= form_for @bill do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_1" autofocus="autofocus" class="form-control" >
        <option value="">Select Category </option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>">
            <%= category.name %>
          </option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :company, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_company" class="form-control" >
        <option value="">Select Company </option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :model, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_model" class="form-control" >
        <option value="">Select Model </option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :father_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :father_name, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :address, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :mobile_no, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :mobile_no, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
    <input autofocus="autofocus" class="form-control" type="number" name="actual_price" id="actual_price" disabled="true">
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'discount (%)', class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
    <input autofocus="autofocus" class="form-control" type="number" name="discount" id="discount">
    </div>
  </div>

  <div class="form-group">
    <%= f.label :total_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <input autofocus="autofocus" class="price form-control" type="number" name="total_price" disabled="true">
      <%= f.hidden_field :price, class: "price" %>
    </div>
  </div>

  <%= f.hidden_field :item_id, class: "model" %><br />
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">

  $(document).ready(function() {
    $("#select_1").on("change",function() {
      var category = $('select#select_1 :selected').val();
      $.ajax({
        url:  '/set_items',
        data: ('id=' + category),
        type: "GET",
        dataType: "script"
      });
    });
    $("#select_company").on("change",function() {
      var company = $('select#select_company :selected').val();
      $.ajax({
        url:  '/set_items',
        data: ('id=' + company),
        type: "GET",
        dataType: "script"
      });
    });
    $("#select_model").on("change",function() {
      var model = $('select#select_model :selected').val();
      $.ajax({
        url:  '/set_price',
        data: ('id=' + model),
        type: "GET",
        dataType: "script"
      });
      $('.model').val(model)
    });
    $("#discount").on("change",function() {
      var discount = $('#discount').val();
      var price = $('#actual_price').val();
      console.log(discount, price)
      discount = (discount * price)/100;
      $('.price').val(price - discount);
    });
  });
</script>

app/views/categories/index.html.erb
<h2>Categories</h2>
<%= link_to 'Add Category', new_category_path, class: "text-primary" %>
<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Category </th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <th><%= sr %></th>
          <td><%= category.name %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
    </tbody>
  </table>
</ul>

app/views/categories/new.html.erb
<h2>Create Category</h2><hr>
<%= form_with url: categories_path do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :item_type, value: 'category' %><br />
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/companies/_set_items.html.erb
<% if @items.blank? %>
  <option value=""> Please Add <%= @items.last.item_type.camelize %> First </option>
<% else %>
  <option value="">Select <%= @items.last.item_type.camelize %> </option>
  <% @items.each do |item| %>
    <option value="<%= item.id %>">
      <%= item.name %>
    </option>
  <% end %>
<% end %>

app/views/companies/index.html.erb
<h2>Companies</h2>
<%= link_to 'Add Company', new_company_path, class: "text-primary" %>
<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Category </th>
        <th> Company </th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <th><%= sr %></th>
          <td><%= company.parrent.name %></td>
          <td><%= company.name %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
    </tbody>
  </table>
</ul>

app/views/companies/new.html.erb
<h2>Create Company</h2><hr>
<%= form_with url: companies_path do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% @company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= select_tag :parrent_id, options_from_collection_for_select(@categories, "id", "name"), autofocus: true,
                                class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :item_type, value: 'company' %><br />
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/companies/set_items.js.erb
$("#select_<%=@items.last.item_type%>").html("<%= j render partial: "set_items" %>");

app/views/companies/set_price.js.erb
$('#actual_price').val(<%= @price %>);

app/views/imported_items/index.html.erb
<h2>Imported Item</h2>
<%= link_to 'Add Imported Item', new_imported_item_path, class: "text-primary" %>

<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Catagory </th>
        <th> Company </th>
        <th> Model </th>
        <th> Imported Date </th>
        <th> Quentity </th>
        <th> Price Per Unit </th>
        <th> Total Price </th>
      </tr>
    </thead>
    <tbody>
      <% @imported_items.each do |imported_item| %>
        <tr>
          <th><%= sr %></th>
          <td><%= imported_item.item.parrent.parrent.name %></td>
          <td><%= imported_item.item.parrent.name %></td>
          <td><%= imported_item.item.name %></td>
          <td><%= imported_item.imported_date.strftime("%d/%m/%y") %></td>
          <td><%= imported_item.quantity %></td>
          <td><%= imported_item.price_per_unit %></td>
          <td><%= imported_item.total_price %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
    </tbody>
  </table>
</ul>

app/views/imported_items/new.html.erb
<h2>Create Company</h2><hr>
<%= form_for @imported_item do |f| %>
  <% if @imported_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imported_item.errors.count, "error") %> prohibited this imported_item from being saved:</h2>

      <ul>
        <% @imported_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_1" class="form-control" >
        <option value="">Select Category </option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>">
            <%= category.name %>
          </option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :company, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_company" class="form-control" >
        <option value="">Select Company </option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :model, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_model" class="form-control" >
        <option value="">Select Model </option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :imported_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.date_field :imported_date, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quantity, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :quantity, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price_per_unit, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :price_per_unit, autofocus: true,
                                class: "price_per_unit form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label 'profit (%)', class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.number_field :profit, autofocus: true,
                            class: "profit form-control" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label 'final price per unit', class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
    <input autofocus="autofocus" class="form-control" type="number" id="final-price">
    </div>
  </div>

  <%= f.hidden_field :item_id, class: "model" %><br />
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">

  $(document).ready(function() {
    $("#select_1").on("change",function() {
      var category = $('select#select_1 :selected').val();
      $.ajax({
        url:  '/set_items',
        data: ('id=' + category),
        type: "GET",
        dataType: "script"
      });
    });
    $("#select_company").on("change",function() {
      var company = $('select#select_company :selected').val();
      $.ajax({
        url:  '/set_items',
        data: ('id=' + company),
        type: "GET",
        dataType: "script"
      });
    });
    $("#select_model").on("change",function() {
      var model = $('select#select_model :selected').val();
      $('.model').val(model)
    });
    $(".profit").on("change",function() {
      var profit = $('.profit').val();
      var price = $('.price_per_unit').val();
      final_price = (profit * price)/100;
      $('#final-price').val(parseInt(price) + parseInt(final_price));
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swastik Mobile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    ></script>
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light
              navbar-inverse navbar-fixed-top mb-4">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <h3 class="text-primary"> <%= current_user.name %> </h3>
        <% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Check Stock', stocks_path, class: 'nav-link text-primary' %>
          </li>
          <li class="nav-item <%= root_path %>">
            <%= link_to 'Categories', categories_path, class: "nav-link text-primary" %>
          </li>
          <% categories = Item.where(item_type: 'category') %>
          <% unless categories.blank? %>
            <li class="nav-item <%= root_path %>">
              <%= link_to 'Companies', companies_path, class: "nav-link text-primary" %>
            </li>
            <li class="nav-item <%= root_path %>">
              <%= link_to 'Models', models_path, class: "nav-link text-primary" %>
            </li>
            <li class="nav-item <%= root_path %>">
              <%= link_to 'Imported Item', imported_items_path, class: "nav-link text-primary" %>
            </li>
          <% end %>
          <li class="nav-item <%= root_path %>">
            <%= link_to 'Bills', bills_path, class: "nav-link text-primary" %>
          </li>
        </ul>
        <div class="pull-right">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%#= link_to friend_requests_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%#= link_to messages_path(nav_bar: false), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%#= link_to user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Log-Out', destroy_user_session_path, method: :delete, class: "nav-link text-danger" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
  <div class='container' role='main'>
    <%= yield %>
  </div>

app/views/models/index.html.erb
<h2>Models</h2>
<%= link_to 'Add Model', new_model_path, class: "text-primary" %>
<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Category </th>
        <th> Company </th>
        <th> Model </th>
      </tr>
    </thead>
    <tbody>
      <% @models.each do |model| %>
        <tr>
          <th><%= sr %></th>
          <td><%= model.parrent.parrent.name %></td>
          <td><%= model.parrent.name %></td>
          <td><%= model.name %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
    </tbody>
  </table>
</ul>

app/views/models/new.html.erb
<h2>Create Company</h2><hr>
<%= form_with url: models_path do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% @model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_1" class="form-control" >
        <option value="">Select Category </option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>">
            <%= category.name %>
          </option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :company, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <select id="select_2" class="form-control" >
        <option value="">Select On Time </option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :model, class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, autofocus: true,
                                class: "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :parrent_id, class: "company" %>
  <%= f.hidden_field :item_type, value: 'company' %><br />
  <div class="form-group">
    <div class="col-sm-6 col-sm-offset-2">
      <%= f.submit "Create", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">

  $(document).ready(function() {
    $("#select_1").on("change",function() {
      var category = $('select#select_1 :selected').val();
      $.ajax({
        url:  '/set_companies',
        data: ('id=' + category),
        type: "GET",
        dataType: "script"
      });
    });
    $("#select_2").on("change",function() {
      var company = $('select#select_2 :selected').val();
      $('.company').val(company)
    });
  });
</script>

app/views/stocks/index.html.erb
<h2>Total Stocks</h2>

<hr>
<ul class="navbar-nav">
  <% sr = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th> SR </th>
        <th> Catagory </th>
        <th> Company </th>
        <th> Model </th>
        <th> Total Item </th>
      </tr>
    </thead>
    <tbody>
      <% sort_stocks(@stocks).each do |stock| %>
        <tr>
          <th><%= sr %></th>
          <td><%= stock.item.parrent.parrent.name %></td>
          <td><%= stock.item.parrent.name %></td>
          <td><%= stock.item.name %></td>
          <td><%= stock.quantity %></td>
        </tr>
        <% sr = sr + 1 %>
      <% end %>
    </tbody>
  </table>
</ul>